CREATE TABLE users
(
    id            int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(64) UNIQUE NOT NULL,
    email         VARCHAR(128) UNIQUE,
    password_hash VARCHAR(255),
    role          VARCHAR(20)        NOT NULL DEFAULT 'USER',
    telegram_id   BIGINT UNIQUE,
    avatar_url    VARCHAR(512),
    display_name  VARCHAR(128),
    created_at    TIMESTAMP          NOT NULL DEFAULT NOW()
);

CREATE TABLE categories
(
    id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(64)        NOT NULL,
    slug        VARCHAR(64) UNIQUE NOT NULL,
    unit        VARCHAR(32)        NOT NULL,
    description VARCHAR(256),
    rules       TEXT
);

CREATE TABLE results
(
    id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    category_id BIGINT         NOT NULL REFERENCES categories (id),
    value       NUMERIC(10, 2) NOT NULL CHECK (value > 0),
    approved    BOOLEAN        NOT NULL DEFAULT FALSE,
    note        VARCHAR(512),
    recorded_at TIMESTAMP      NOT NULL DEFAULT NOW(),
    created_at  TIMESTAMP      NOT NULL DEFAULT NOW()
);

CREATE TABLE one_rep_results
(
    id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    bench       NUMERIC(10, 2) NOT NULL CHECK (bench > 0),
    bicep       NUMERIC(10, 2) NOT NULL CHECK (bicep > 0),
    pullups     NUMERIC(10, 2) NOT NULL CHECK (pullups > 0),
    total       NUMERIC(10, 2) GENERATED ALWAYS AS (bench + bicep + pullups) STORED,
    approved    BOOLEAN        NOT NULL DEFAULT FALSE,
    note        VARCHAR(512),
    recorded_at TIMESTAMP      NOT NULL DEFAULT NOW(),
    created_at  TIMESTAMP      NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_results_user_id ON results (user_id);
CREATE INDEX idx_results_category_id ON results (category_id);
CREATE INDEX idx_one_rep_results_user_id ON one_rep_results (user_id);